# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def swiftPods
  pod 'Alamofire'
  pod 'XCoordinator'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxCoreData'
  pod 'SwiftMessages'
end

target 'elmenus' do
  use_frameworks!
  swiftPods
end
